<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706140801 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE journal_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mood INT NOT NULL, pain_level INT NOT NULL, blood_pressure VARCHAR(20) NOT NULL, note VARCHAR(1000) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C8FAAE5A6B899279 ON journal_entry (patient_id)');
        $this->addSql('CREATE INDEX IDX_C8FAAE5AF675F31B ON journal_entry (author_id)');
        $this->addSql('ALTER TABLE journal_entry ADD CONSTRAINT FK_C8FAAE5A6B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE journal_entry ADD CONSTRAINT FK_C8FAAE5AF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE journal_entry DROP CONSTRAINT FK_C8FAAE5A6B899279');
        $this->addSql('ALTER TABLE journal_entry DROP CONSTRAINT FK_C8FAAE5AF675F31B');
        $this->addSql('DROP TABLE journal_entry');
    }
}
