<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706211047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE journal_entry_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text VARCHAR(1000) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, journal_entry_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E226D496A86E4FB ON journal_entry_comment (journal_entry_id)');
        $this->addSql('CREATE INDEX IDX_5E226D49F675F31B ON journal_entry_comment (author_id)');
        $this->addSql('ALTER TABLE journal_entry_comment ADD CONSTRAINT FK_5E226D496A86E4FB FOREIGN KEY (journal_entry_id) REFERENCES journal_entry (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE journal_entry_comment ADD CONSTRAINT FK_5E226D49F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE journal_entry_comment DROP CONSTRAINT FK_5E226D496A86E4FB');
        $this->addSql('ALTER TABLE journal_entry_comment DROP CONSTRAINT FK_5E226D49F675F31B');
        $this->addSql('DROP TABLE journal_entry_comment');
    }
}
