<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708134330 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

        // Le passage d'un horaire unique par traitement à plusieurs horaires
        // (TreatmentSchedule) rend les prises existantes incompatibles avec
        // le nouveau schéma. Ces tables ne contiennent que des données de
        // fixtures de dev (voir AppFixtures), donc on les vide plutôt que de
        // tenter une migration de données : `doctrine:fixtures:load` les
        // regénère dans le nouveau format.
        $this->addSql('TRUNCATE TABLE treatment CASCADE');

        $this->addSql(<<<'SQL'
            CREATE TABLE treatment_schedule (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              scheduled_time VARCHAR(5) NOT NULL,
              treatment_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C89259A2471C0366 ON treatment_schedule (treatment_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              treatment_schedule
            ADD
              CONSTRAINT FK_C89259A2471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) NOT DEFERRABLE
        SQL);
        $this->addSql('ALTER TABLE treatment DROP scheduled_time');
        $this->addSql('ALTER TABLE treatment_intake DROP CONSTRAINT fk_6fa9e932471c0366');
        $this->addSql('DROP INDEX idx_6fa9e932471c0366');
        $this->addSql('DROP INDEX uniq_treatment_intake_date');
        $this->addSql('ALTER TABLE treatment_intake RENAME COLUMN treatment_id TO treatment_schedule_id');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              treatment_intake
            ADD
              CONSTRAINT FK_6FA9E932C9C55883 FOREIGN KEY (treatment_schedule_id) REFERENCES treatment_schedule (id) NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX IDX_6FA9E932C9C55883 ON treatment_intake (treatment_schedule_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_treatment_intake_schedule_date ON treatment_intake (treatment_schedule_id, date)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs

        // Même raisonnement que dans up() : impossible de reconstruire un
        // scheduled_time unique à partir de N schedules par traitement, donc
        // on repart d'une table treatment vide (fixtures de dev uniquement).
        $this->addSql('TRUNCATE TABLE treatment CASCADE');

        $this->addSql('ALTER TABLE treatment_schedule DROP CONSTRAINT FK_C89259A2471C0366');
        $this->addSql('DROP TABLE treatment_schedule');
        $this->addSql('ALTER TABLE treatment ADD scheduled_time VARCHAR(5) NOT NULL');
        $this->addSql('ALTER TABLE treatment_intake DROP CONSTRAINT FK_6FA9E932C9C55883');
        $this->addSql('DROP INDEX IDX_6FA9E932C9C55883');
        $this->addSql('DROP INDEX uniq_treatment_intake_schedule_date');
        $this->addSql('ALTER TABLE treatment_intake RENAME COLUMN treatment_schedule_id TO treatment_id');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              treatment_intake
            ADD
              CONSTRAINT fk_6fa9e932471c0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('CREATE INDEX idx_6fa9e932471c0366 ON treatment_intake (treatment_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_treatment_intake_date ON treatment_intake (treatment_id, date)');
    }
}
