<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260707135214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE treatment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, dosage VARCHAR(100) NOT NULL, scheduled_time VARCHAR(5) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, prescribed_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98013C316B899279 ON treatment (patient_id)');
        $this->addSql('CREATE INDEX IDX_98013C31424D1A3F ON treatment (prescribed_by_id)');
        $this->addSql('CREATE TABLE treatment_intake (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, taken BOOLEAN NOT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, treatment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FA9E932471C0366 ON treatment_intake (treatment_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_treatment_intake_date ON treatment_intake (treatment_id, date)');
        $this->addSql('ALTER TABLE treatment ADD CONSTRAINT FK_98013C316B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE treatment ADD CONSTRAINT FK_98013C31424D1A3F FOREIGN KEY (prescribed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE treatment_intake ADD CONSTRAINT FK_6FA9E932471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE treatment DROP CONSTRAINT FK_98013C316B899279');
        $this->addSql('ALTER TABLE treatment DROP CONSTRAINT FK_98013C31424D1A3F');
        $this->addSql('ALTER TABLE treatment_intake DROP CONSTRAINT FK_6FA9E932471C0366');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE treatment_intake');
    }
}
