<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711131657 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ML-55: add failed_login_attempt (admin supervision screen)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE failed_login_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE failed_login_attempt');
    }
}
