<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703085510 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patient_aidant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, aidant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC41B3D56B899279 ON patient_aidant (patient_id)');
        $this->addSql('CREATE INDEX IDX_BC41B3D585BB6C15 ON patient_aidant (aidant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_patient_aidant ON patient_aidant (patient_id, aidant_id)');
        $this->addSql('CREATE TABLE patient_soignant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, soignant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_37950A576B899279 ON patient_soignant (patient_id)');
        $this->addSql('CREATE INDEX IDX_37950A57453B4D3C ON patient_soignant (soignant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_patient_soignant ON patient_soignant (patient_id, soignant_id)');
        $this->addSql('ALTER TABLE patient_aidant ADD CONSTRAINT FK_BC41B3D56B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_aidant ADD CONSTRAINT FK_BC41B3D585BB6C15 FOREIGN KEY (aidant_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_soignant ADD CONSTRAINT FK_37950A576B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_soignant ADD CONSTRAINT FK_37950A57453B4D3C FOREIGN KEY (soignant_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE patient_aidant DROP CONSTRAINT FK_BC41B3D56B899279');
        $this->addSql('ALTER TABLE patient_aidant DROP CONSTRAINT FK_BC41B3D585BB6C15');
        $this->addSql('ALTER TABLE patient_soignant DROP CONSTRAINT FK_37950A576B899279');
        $this->addSql('ALTER TABLE patient_soignant DROP CONSTRAINT FK_37950A57453B4D3C');
        $this->addSql('DROP TABLE patient_aidant');
        $this->addSql('DROP TABLE patient_soignant');
    }
}
